### ISSUE TITLE
Compatibility with parcel 1.12.x

### ISSUE THREAD

**Issue by belicekm** [belicekm/parcel-plugin-handlebars-precompile#5]
When building using globally installed `parcel-bundler@1.12.x` there is following error related to source maps generation:

```
×  D:\projects\test-parcel-plugin-static-js\test.hbs: "version" is a required argument.
    at Object.getArg (C:\Users\mirek\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\source-map\lib\util.js:24:11)
    at new BasicSourceMapConsumer (C:\Users\mirek\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\source-map\lib\source-map-consumer.js:294:22)
    at new SourceMapConsumer (C:\Users\mirek\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\source-map\lib\source-map-consumer.js:22:7)
    at SourceMap.getConsumer (C:\Users\mirek\AppData\Roaming\npm\node_modules\parcel-bundler\src\SourceMap.js:38:12)
    at SourceMap.extendSourceMap (C:\Users\mirek\AppData\Roaming\npm\node_modules\parcel-bundler\src\SourceMap.js:149:29)
    at JSAsset.generate (C:\Users\mirek\AppData\Roaming\npm\node_modules\parcel-bundler\src\assets\JSAsset.js:159:50)
    at JSAsset.process (C:\Users\mirek\AppData\Roaming\npm\node_modules\parcel-bundler\src\Asset.js:216:35)
```

**Comment by cgsawtell** [comment]
I'm using parcel 1.12.4 and this doesn't seem to be an issue for me btw.

**Comment by rgraffbrd** [comment]
@belicekm You have to use the `--no-source-maps` flag with Parcel. It's a huge caveat if you ask me, but that's what this plugin support right now I guess 🤪

**Comment by maxlath** [comment]
I encountered the same issue, and got it to work by applying this patch https://github.com/aevanson/parcel-plugin-handlebars-precompile/commit/f9c19b0

The source map still seems to fail for Handlebars templates, but at least it works without having to disable all source maps (`parcel --no-source-maps`)

That's quite sad as [Handlebars does generate source maps](https://handlebarsjs.com/api-reference/compilation.html#handlebars-precompile-template-options), but I couldn't get it to work:
```js
const { code: precompiled, map } = precompile(this.contents, { srcName: this.relativeName })

// When extending JSAsset: fails
this.sourceMap = JSON.parse(map);

// OR When extending Asset (see @aevanson's patch referenced above): fails
return [{
    type: 'js',
    value: code,
    sourceMap: JSON.parse(map)
}];
```
I guess the fact that there are some additional wrapper code in `generate` would break the source map anyway(?)
